### ISSUE TITLE
Node.jsで実行できません。

### ISSUE THREAD

**Issue by O2giriOC** [miso-develop/opniz-sdk-nodejs#4]
![画像3](https://user-images.githubusercontent.com/120290104/207199179-5f15d332-d1e9-4d3a-b002-bac08a4da91e.png)

M5atomliteを使用しています。
opniz uploadでopniz CLIを書き込めはしたのですが、いざNode.jsで動かそうとすると「opniz.connect is not a function」 と表示されてしまいます。これはopnizインスタンスを生成できていない、またはopniz自体をインストールできていないということでしょうか。
素人丸出しの質問で申し訳ありませんが、教えていただければ幸いです。

**Comment by miso-develop** [comment]
お試しいただきありがとうございます！！

おそらくREADMEにある最初のコードを実行いただいたかと思います。
大変申し訳ないのですが、こちら前回のアップデートでの変更をREADMEへ反映しきれていない状態でした。

以下のコードでしたら実行できるかと思いますので、お手数おかけし恐縮ですがお試しいただけますでしょうか。
（`await opniz.connect()`を`await opniz.connectWait()`に変更しています）

```
const { Opniz } = require("opniz")

const port = 3000 // 任意のポートを指定（opnizデバイスの指定と合わせる）

; (async () => {
	const opniz = new Opniz.Esp32({ port }) // opnizインスタンス生成
	await opniz.connectWait()               // opnizデバイスへ接続
	console.log(await opniz.getFreeHeap())  // opnizデバイスのヒープメモリーサイズを取得して表示
})()
```

**Comment by miso-develop** [comment]
READMEとexamplesのコードを修正しました！
issueいただき助かりました！ありがとうございます！

**Comment by O2giriOC** [comment]
回答ありがとうございます！！
関数自体のエラーは出なくなったのですが、
「Not connected」とのエラーが出てしまいました笑。
こちらのAtomliteに問題があると思うのですが、重ね重ね恐縮ですが、何かご意見いただけませんでしょうか。

**Comment by miso-develop** [comment]
一歩前進しましたね！良かったです！
M5ATOM Liteとの接続ができていないようなので、以下の情報を確認いただけますでしょうか？

### M5ATOM LiteとNode.jsを実行しているPCは同じネットワーク上にありますでしょうか？
PCからM5ATOM Liteに対してpingが通る状態でなければいけません。
M5ATOM LiteのIPアドレスはopniz CLIのmonitorコマンドにて確認できます。
コマンド実行後にM5ATOM Liteを再起動し、Wi-Fiに接続されるとIPアドレスが表示されます。

```
$ opniz monitor
? デバイスのシリアルポートを選択してください: COM8
,3��WiFi connecting............
WiFi connected: 192.168.1.100
```

### opniz CLIのuploadコマンド実行時の入力情報のうち、以下の情報をご確認ください
* 「opnizプログラム実行マシンのIPアドレス」がNode.js実行PCのIPアドレスであること
* 「opnizプログラムのポート番号」が`3000`となっていること
	* サンプルプログラムのポート番号は`3000`を指定しています
	* opniz CLIのuploadコマンドではデフォルトで`3000`を指定するようになっています

**Comment by O2giriOC** [comment]
暖かいお言葉ありがとうございます。
monitorコマンドを実行してみたところ、接続中のままでIPアドレスが表示されない状態になってしまいました。
![スクリーンショット 2022-12-13 212146](https://user-images.githubusercontent.com/120290104/207317072-2b81219c-7d62-402a-be33-45c302c4658c.png)

実行PCのIPアドレスは固定しているので、恐らくAtomliteとIPアドレスが違っていることはないのではないかと思います。
またポート番号ですが毎回3000にしているので多分大丈夫です笑。

**Comment by miso-develop** [comment]
ご確認ありがとうございます！
WiFi connecting...から進んでいないのでWi-Fiへの接続ができていないようです。
原因としてはopniz CLIでのupload時に入力したWi-Fi SSIDまたはパスワードが誤っている可能性があります。
もう一度uploadコマンドを実行し再入力をお試しいただけますでしょうか！

**Comment by O2giriOC** [comment]
遅くなってしまいすみません！
あの後何度か実行してみましたが、同じようにIPアドレスが表示されないまま「WiFi connecting」が表示されてたままでした…。
一応M5Bunerでは件のWiFiに接続できたので、WiFiと繋がらないことはないと思うのですが、どうでしょうか。

**Comment by miso-develop** [comment]
そうですか…
Wi-Fi接続できない原因として他に考えられる点としてはM5ATOMがWi-Fi感度が低いハードウェアバグがあったりするので、Wi-Fiルーターの近くで試してみるといったあたりですかね…
（M5BunerでWi-Fi接続できていたのでしたら可能性は低そうですが…）

あとはopniz CLIでのupload時に入力情報を引数指定できますので、以下の形式で`<ssid>`、`<password>`、`<address>`をコマンド実行時点で明示的に入力する方法もあります。

```
$ opniz upload -s <ssid> -p <password> -a <address> -d m5atom -P 3000
```

それと以下のコマンドでopniz CLIのバージョンが確認できますので、念のため使用いただいているバージョンを教えていただけますでしょうか！

```
$ opniz -v
```

**Comment by O2giriOC** [comment]
接続するWiFiを5GHz帯に変更したら実行できました！
しょうもない解決のために試行錯誤していただき本当にありがとうございました！！
ちなみにopniz CLIのバージョンは「0.3.5」でした。
![スクリーンショット 2022-12-14 180107](https://user-images.githubusercontent.com/120290104/207553125-b0455683-926e-4ee5-9b24-e85d643f9979.png)

**Comment by O2giriOC** [comment]
接続するWiFiを5GHz帯に変更したら実行できました！
しょうもない解決のために試行錯誤していただき本当にありがとうございました！！
ちなみにopniz CLIのバージョンは「0.3.5」でした。
![スクリーンショット 2022-12-14 180107](https://user-images.githubusercontent.com/120290104/207553787-aaf7dfe9-b436-4fff-a73f-227b4c686f8e.png)

最後に1つお聞きしたいのですが、環境センサなどの周辺機器を動作させる予定はありますでしょうか？
もしよければお聞きしたいです。

**Comment by miso-develop** [comment]
無事解決できてよかったです！
（ただM5ATOM Liteはたしか5GHz帯に対応していなかった気も…）

> 最後に1つお聞きしたいのですが、環境センサなどの周辺機器を動作させる予定はありますでしょうか？

digitalRead/WriteやanalogReadといった基本メソッドをサポートしていますのでこれらのメソッドから制御できます！
[（参考）opniz.M5ATOMクラスのドキュメント](https://miso-develop.github.io/opniz-sdk-nodejs/classes/devices_M5Atom.M5Atom.html)

たとえば実際に私が使っているものですが照度センサをM5ATOM Liteの3.3Vと33番ホールに挿して`await opniz.analogRead(33)`とすると明るさが取得できます。

またArduinoライブラリと組み合わせてCO2センサーの値を取得したりもしています。
（opniz Arduinoライブラリを拡張実装するためopniz CLIは使用できませんが…）
[（参考）opnizでつくる「CO2センサ（MH-Z19C）データのGoogle Spreadsheetsロギングシステム」（Qiita）](https://qiita.com/miso_develop/items/287706aa12e84d687c20)

もしobnizのパーツライブラリのようなものを指しているようでしたら、いずれは同じような仕組みも実装したいと考えています！

**Comment by miso-develop** [comment]
一旦こちらのIssueはクローズとさせていただきますが、他にもご不明点等あればこちらや別のIssueでも大丈夫ですのでコメントいただければと思います！

**Comment by O2giriOC** [comment]
おっしゃる通り5GHzではなく2.4GHz帯に変更したおかげで動かすことができました。
そうでしたね、analogreadを使えばいいんでしたね、すっかり忘れていました…。
至れり尽くせりで本当に助かりました、ありがとうございます。

**Comment by O2giriOC** [comment]
お久しぶりです、また質問失礼します。
今ENV3センサを使用していまして、センサ値が受信される26番ピンをanalogreadしていたのですが、0としか表示されません。
ENV3は湿度、気圧、温度を測定していて、I2Cで通信しているので、専用の関数じゃないと値を取得できないということでしょうか。
また教えていただければ幸いです。
